### ISSUE TITLE
Add nested label / checkbox/radio margin

### ISSUE THREAD

**Issue by inoas** [mblode/marx#26]
When placing nested checkboxes on the left they are directly glued to the text.

```css
label > input:first-child[type="checkbox"],
label > input:first-child[type="radio"] {
    margin-right: 2px;
}
```

Could this be added? I do not have stylus running on osx via brew. I can add the change for css, css.min and scss. Interested @mblode?
